# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Home
tagline:          ''
description:      ''
url:              https://busara-s.github.io/
baseurl:          https://busara-s.github.io/

author:
  name:           'Busara Saelim'
  linkedin:       'busara-saelim-011920a9'
  email:          'busara.saelim@gmail.com'

paginate:         4   

github:
  repo:           https://github.com/busara-s/busara-s.github.io
